### ISSUE TITLE
Avez vous testé avec OpenStack Magnum ?

### ISSUE THREAD

**Issue by RemiBou** [itwars/docker-swarm#2]
Bonjour,

Merci pour ce post très utile, notemment pour al partie openstack. OpenStack a aussi un projet appelé Magnum qui permet de gérer des cluster d'orchestrateur de container. Est ce que vous l'avez testé ?  https://docs.openstack.org/magnum/latest/user/index.html#swarm ça a l'air sympa pour mettre en place l'ip flottante entre les master et la gestion des volumes via rexray et cinder.

**Comment by itwars** [comment]
Bonjour,
Non, je n'ai pas eu l'occasion de faire de l'openstack, mis à part sur l'offre de OVH.
